name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: WebHook
        run: curl https://2b2t.asia:10000/generic-webhook-trigger/invoke?token=mirai-http-sdk --insecure
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      - name: Get Short CommitID
        id: vars
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Checking Short CommitID
        run: echo ${SHORT_SHA}
      - name: "Rendering README"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          GLOBAL_TEMPLATE_REPOSITORY: "{repository-owner}/{repository-name}"
          files: |
            template/README.md=README.md
          committer_name: README-READER[bot]
          committer_email: README-READER[bot]@users.noreply.github.com
          commit_message: '[ci skip] Auto Rending: README'
          confirm_and_push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}